// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJJ4gSxXSA2r7bhxXEXdSjJhrrE2krtY8',
    appId: '1:374082068086:android:7cf495b5147a3777714957',
    messagingSenderId: '374082068086',
    projectId: 'hotelini',
    storageBucket: 'hotelini.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCInhuVYWusf0TxE09HC1wiU9FvsJFXT6A',
    appId: '1:374082068086:ios:dc403bbda5b8c69d714957',
    messagingSenderId: '374082068086',
    projectId: 'hotelini',
    storageBucket: 'hotelini.appspot.com',
    iosBundleId: 'com.example.nextApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF13ygQVO2pyYJtvvu46PQq_yBVgg8aJ4',
    appId: '1:374082068086:web:30cae1b9a9614cf6714957',
    messagingSenderId: '374082068086',
    projectId: 'hotelini',
    authDomain: 'hotelini.firebaseapp.com',
    storageBucket: 'hotelini.appspot.com',
    measurementId: 'G-LKWWNV8KYM',
  );

}